version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: threads_mongodb
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=threads_db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  threadsposter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: threads_poster
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/threads_db
      - MONGODB_DB_NAME=threads_db
    volumes:
      - ./logs:/app/logs
    depends_on:
      mongodb:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local 