name: Threads 機器人

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分鐘運行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  run-bot:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4
    
    - name: 設定 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: 安裝相依套件
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: 設定環境變數
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "THREADS_ACCESS_TOKEN=${{ secrets.THREADS_ACCESS_TOKEN }}" >> .env
        echo "THREADS_APP_ID=${{ secrets.THREADS_APP_ID }}" >> .env
        echo "THREADS_APP_SECRET=${{ secrets.THREADS_APP_SECRET }}" >> .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "MONGODB_DB=threads_poster" >> .env
        echo "MONGODB_COLLECTION=posts" >> .env
        echo "POSTING_TIMEZONE=Asia/Taipei" >> .env
        echo "CHECK_INTERVAL=60" >> .env
        echo "RETRY_INTERVAL=300" >> .env
    
    - name: 執行機器人
      run: |
        python src/main.py
      env:
        PYTHONPATH: ${{ github.workspace }}
        PYTHONUNBUFFERED: 1 