name: Threads Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # 每5分鐘運行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .env file
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "THREADS_ACCESS_TOKEN=${{ secrets.THREADS_ACCESS_TOKEN }}" >> .env
        echo "THREADS_APP_ID=${{ secrets.THREADS_APP_ID }}" >> .env
        echo "THREADS_APP_SECRET=${{ secrets.THREADS_APP_SECRET }}" >> .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "MONGODB_DB_NAME=threads_bot" >> .env
        echo "POSTING_TIMEZONE=Asia/Taipei" >> .env
        echo "MIN_REPLY_INTERVAL=300" >> .env
        echo "MAX_REPLY_INTERVAL=3600" >> .env
    
    - name: Run bot
      run: python -m src.main 