name: 部署 ThreadsPoster

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # 每6小時執行一次

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4
    
    - name: 設定 Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: 安裝相依套件
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov black flake8 isort mypy
        
    - name: 執行程式碼格式檢查
      run: |
        black --check src tests
        flake8 src tests
        isort --check-only src tests
        mypy src
        
    - name: 執行測試
      run: |
        pytest tests/ \
          --cov=src \
          --cov-report=xml \
          --cov-report=html \
          --junitxml=test-results.xml \
          -v
      env:
        PYTHONPATH: ${{ github.workspace }}
        MONGODB_URI: mongodb://localhost:27017
        
    - name: 上傳測試覆蓋率報告
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - uses: actions/checkout@v4
    
    - name: 設定 Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        
    - name: 安裝相依套件
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 設定環境變數
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "THREADS_APP_ID=${{ secrets.THREADS_APP_ID }}" >> .env
        echo "THREADS_APP_SECRET=${{ secrets.THREADS_APP_SECRET }}" >> .env
        echo "THREADS_ACCESS_TOKEN=${{ secrets.THREADS_ACCESS_TOKEN }}" >> .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        
    - name: 執行程式
      run: |
        python src/main.py &
      env:
        PYTHONUNBUFFERED: 1

    - name: 監控程式
      run: |
        sleep 300  # 等待5分鐘
        if ! pgrep -f "python src/main.py"; then
          echo "程式已停止運行"
          exit 1
        fi 