name: ThreadsPoster CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '*/5 * * * *'  # 每5分鐘運行一次
  workflow_dispatch:  # 允許手動觸發

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4
    
    - name: 設定 Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: 安裝相依套件
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov black flake8 isort mypy bandit safety
        
    - name: 執行程式碼格式檢查
      run: |
        black --check src tests
        flake8 src tests
        isort --check-only src tests
        mypy src
        
    - name: 執行安全掃描
      run: |
        bandit -r src/
        safety check
        
    - name: 執行測試
      run: |
        pytest tests/ \
          --cov=src \
          --cov-report=xml \
          --cov-report=html \
          --junitxml=test-results.xml \
          -v
      env:
        PYTHONPATH: ${{ github.workspace }}
        MONGODB_URI: mongodb://localhost:27017
        
    - name: 上傳測試覆蓋率報告
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: true
        
    - name: 上傳測試結果
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.python-version }}
        path: |
          test-results.xml
          htmlcov/

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'schedule' || github.event_name == 'workflow_dispatch')

    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4
    
    - name: 設定 Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
        
    - name: 安裝相依套件
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 設定環境變數
      run: |
        echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
        echo "THREADS_APP_ID=${{ secrets.THREADS_APP_ID }}" >> .env
        echo "THREADS_APP_SECRET=${{ secrets.THREADS_APP_SECRET }}" >> .env
        echo "THREADS_ACCESS_TOKEN=${{ secrets.THREADS_ACCESS_TOKEN }}" >> .env
        echo "MONGODB_URI=${{ secrets.MONGODB_URI }}" >> .env
        echo "MONGODB_DB=threads_poster" >> .env
        echo "MONGODB_COLLECTION=posts" >> .env
        echo "POSTING_TIMEZONE=Asia/Taipei" >> .env
        echo "CHECK_INTERVAL=60" >> .env
        echo "RETRY_INTERVAL=300" >> .env
        
    - name: 執行機器人
      run: |
        python src/main.py &
        sleep 300  # 等待5分鐘
        if ! pgrep -f "python src/main.py"; then
          echo "程式已停止運行"
          exit 1
        fi
      env:
        PYTHONPATH: ${{ github.workspace }}
        PYTHONUNBUFFERED: 1

  notify:
    needs: [test, deploy]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: 檢查結果
      run: |
        if [[ "${{ needs.test.result }}" == "failure" || \
              "${{ needs.deploy.result }}" == "failure" ]]; then
          echo "工作流程失敗"
          exit 1
        fi 