name: ThreadsPoster CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 */6 * * *'  # 每6小時運行一次

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    steps:
    - uses: actions/checkout@v4
    
    - name: 設定 Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: 安裝依賴
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: 建立環境變數
      run: |
        echo "OPENAI_PROJECT_API_KEY=${{ secrets.OPENAI_PROJECT_API_KEY }}" >> .env
        echo "OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}" >> .env
        echo "THREADS_APP_ID=${{ secrets.THREADS_APP_ID }}" >> .env
        echo "THREADS_APP_SECRET=${{ secrets.THREADS_APP_SECRET }}" >> .env
        echo "THREADS_ACCESS_TOKEN=${{ secrets.THREADS_ACCESS_TOKEN }}" >> .env
        echo "THREADS_USER_ID=${{ secrets.THREADS_USER_ID }}" >> .env
        echo "MONGODB_URI=mongodb://localhost:27017/threads_db" >> .env
        echo "TIMEZONE=Asia/Taipei" >> .env
        echo "LOG_LEVEL=INFO" >> .env
        
    - name: 建立必要目錄
      run: |
        mkdir -p logs
        mkdir -p data
        mkdir -p data/backups
        
    - name: 運行測試
      run: |
        python -m pytest tests/test_system.py -v
        
    - name: 運行系統
      if: github.event_name == 'schedule'  # 只在排程觸發時運行
      run: |
        python src/main.py &
        sleep 300  # 運行5分鐘後停止
        
    - name: 上傳日誌
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs
        path: logs/
        
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - name: 部署通知
      run: |
        echo "系統已成功部署到最新版本" 