name: ThreadsPoster 自動化工作流程

on:
  schedule:
    - cron: '0 12-18 * * *'  # 每日台灣時間20:00-02:00(UTC+8)範圍內每小時執行一次
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '.gitignore'
  workflow_dispatch:  # 允許手動觸發

env:
  PYTHON_VERSION: "3.11"
  TIMEZONE: "Asia/Taipei"
  LOG_LEVEL: "INFO"
  MAX_POSTS_PER_DAY: "5"  # 每日最大發文數，與代碼中的設定一致
  MAX_MEMORY_USAGE: "80"  # 最大記憶體使用百分比
  EXECUTION_TIMEOUT: "1200"  # 執行超時時間（秒）
  POSTING_HOURS_START: "20"  # 發文開始時間（24小時制）
  POSTING_HOURS_END: "26"  # 發文結束時間（24+2小時制，表示凌晨2點）
  PRIME_TIME_EVENING_START: "21"  # 黃金時段開始時間
  PRIME_TIME_EVENING_END: "25"  # 黃金時段結束時間（24+1小時制，表示凌晨1點）
  VERSION: "1.2.1"  # 當前版本號

jobs:
  deploy-and-run:
    name: 部署與運行 ThreadsPoster v1.2.1
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: 檢出代碼
        uses: actions/checkout@v4
        with:
          fetch-depth: 1  # 減少 Git 歷史以加快檢出

      - name: 設定 Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: 安裝依賴
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements.txt

      - name: 建立日誌目錄
        run: mkdir -p logs

      - name: 建立環境變數檔案
        run: |
          cat << EOF > .env
          # OpenAI API 設定
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          OPENAI_MODEL=gpt-4-0125-preview

          # Threads API 設定
          THREADS_APP_ID=${{ secrets.THREADS_APP_ID }}
          THREADS_APP_SECRET=${{ secrets.THREADS_APP_SECRET }}
          THREADS_ACCESS_TOKEN=${{ secrets.THREADS_ACCESS_TOKEN }}
          THREADS_USER_ID=${{ secrets.THREADS_USER_ID }}

          # MongoDB 設定
          MONGODB_URI=${{ secrets.MONGODB_URI }}
          MONGODB_DB_NAME=threadsposter
          MONGODB_COLLECTION=posts

          # 系統設定
          TIMEZONE=${{ env.TIMEZONE }}
          LOG_LEVEL=${{ env.LOG_LEVEL }}
          DEBUG=False
          MAX_POSTS_PER_DAY=${{ env.MAX_POSTS_PER_DAY }}
          MAX_MEMORY_USAGE=${{ env.MAX_MEMORY_USAGE }}
          
          # 發文時間設定
          POSTING_HOURS_START=${{ env.POSTING_HOURS_START }}
          POSTING_HOURS_END=${{ env.POSTING_HOURS_END }}
          PRIME_TIME_EVENING_START=${{ env.PRIME_TIME_EVENING_START }}
          PRIME_TIME_EVENING_END=${{ env.PRIME_TIME_EVENING_END }}
          
          # 發文間隔設定
          PRIME_TIME_MIN_INTERVAL=1800
          PRIME_TIME_MAX_INTERVAL=3600
          OTHER_TIME_MIN_INTERVAL=5400
          OTHER_TIME_MAX_INTERVAL=10800
          
          # 系統版本
          VERSION=${{ env.VERSION }}
          EOF

      - name: 檢查環境變數
        run: |
          # 創建檢查腳本
          cat > check_env.py << 'EOF'
          """檢查環境變數是否存在並有效"""
          import os
          import sys
          from dotenv import load_dotenv

          # 載入環境變數
          load_dotenv()

          required_vars = [
              "OPENAI_API_KEY",
              "THREADS_ACCESS_TOKEN",
              "THREADS_USER_ID",
              "MONGODB_URI",
              "POSTING_HOURS_START",
              "POSTING_HOURS_END",
              "PRIME_TIME_EVENING_START",
              "PRIME_TIME_EVENING_END"
          ]

          missing_vars = []
          for var in required_vars:
              if not os.getenv(var):
                  missing_vars.append(var)

          if missing_vars:
              print(f"錯誤：缺少以下必要的環境變數: {', '.join(missing_vars)}")
              sys.exit(1)
          else:
              print("環境變數檢查通過")
              sys.exit(0)
          EOF

          # 運行檢查
          python check_env.py

      - name: 初始化資料庫
        run: |
          # 創建初始化腳本
          cat > init_db.py << 'EOF'
          """初始化資料庫連接和集合"""
          import asyncio
          import os
          from dotenv import load_dotenv
          from motor.motor_asyncio import AsyncIOMotorClient
          
          load_dotenv()
          
          async def init_db():
              # 獲取環境變數
              mongo_uri = os.getenv("MONGODB_URI")
              db_name = os.getenv("MONGODB_DB_NAME", "threadsposter")
              collection_name = os.getenv("MONGODB_COLLECTION", "posts")
              
              if not mongo_uri:
                  print("錯誤：未設定 MONGODB_URI 環境變數")
                  return False
                  
              try:
                  # 連接 MongoDB
                  client = AsyncIOMotorClient(mongo_uri)
                  db = client[db_name]
                  
                  # 檢查連接
                  await client.admin.command('ping')
                  
                  # 確保集合存在
                  if collection_name not in await db.list_collection_names():
                      await db.create_collection(collection_name)
                      
                  # 建立索引
                  await db[collection_name].create_index("post_id", unique=True)
                  await db[collection_name].create_index("created_at")
                  
                  print(f"成功連接到資料庫 {db_name} 並建立/確認集合 {collection_name}")
                  return True
              except Exception as e:
                  print(f"資料庫初始化錯誤：{str(e)}")
                  return False
              finally:
                  # 關閉連接
                  if 'client' in locals():
                      client.close()
          
          if __name__ == "__main__":
              result = asyncio.run(init_db())
              if not result:
                  exit(1)
          EOF

          # 運行初始化
          python init_db.py

      - name: 檢查系統資源
        run: |
          # 安裝 psutil 套件
          pip install psutil
          
          # 創建記憶體檢查腳本
          cat > check_memory.py << 'EOF'
          """檢查系統記憶體使用情況"""
          import os
          import psutil
          
          def check_memory_usage():
              # 獲取最大允許的記憶體使用率
              max_usage = float(os.getenv("MAX_MEMORY_USAGE", "80"))
              
              # 獲取當前記憶體使用情況
              memory = psutil.virtual_memory()
              current_usage = memory.percent
              
              print(f"當前記憶體使用率: {current_usage:.1f}% (最大允許: {max_usage:.1f}%)")
              
              # 如果超過最大值，退出
              if current_usage > max_usage:
                  print("警告: 記憶體使用率過高!")
                  return False
              
              return True
          
          if __name__ == "__main__":
              if not check_memory_usage():
                  exit(1)
          EOF
          
          # 運行記憶體檢查
          python check_memory.py

      - name: 運行程式
        env:
          PYTHONPATH: ${{ github.workspace }}
          PYTHONUNBUFFERED: 1
        run: |
          # 創建超時監控腳本
          cat > run_with_timeout.py << 'EOF'
          """運行主程式並監控超時"""
          import os
          import sys
          import time
          import subprocess
          import signal
          import re
          import datetime
          import pytz

          # 設定超時時間
          timeout = int(os.getenv("EXECUTION_TIMEOUT", "1200"))
          timezone = os.getenv("TIMEZONE", "Asia/Taipei")
          
          # 檢查當前時間是否在發文時間範圍內
          def is_posting_time():
              now = datetime.datetime.now(pytz.timezone(timezone))
              hour = now.hour
              
              # 從環境變數獲取發文時間範圍
              posting_start = int(os.getenv("POSTING_HOURS_START", "20"))
              posting_end = int(os.getenv("POSTING_HOURS_END", "26"))
              
              # 處理跨日的發文時間範圍
              if posting_end > 24:
                  end_hour = posting_end - 24
                  if posting_start <= hour < 24 or 0 <= hour < end_hour:
                      print(f"當前時間 {hour}:00 在發文時間範圍內 (晚上{posting_start}:00-凌晨{end_hour}:00)")
                      return True
              else:
                  if posting_start <= hour < posting_end:
                      print(f"當前時間 {hour}:00 在發文時間範圍內 ({posting_start}:00-{posting_end}:00)")
                      return True
                      
              print(f"當前時間 {hour}:00 不在發文時間範圍內 (晚上{posting_start}:00-凌晨{posting_end-24 if posting_end > 24 else posting_end}:00)")
              return False
          
          # 檢查今日發文次數是否已達上限
          def check_post_count():
              max_posts = int(os.getenv("MAX_POSTS_PER_DAY", "5"))
              print(f"今日最大發文次數: {max_posts} (實際次數由系統內部控制為3-5次之間)")
              return True
          
          # 檢查是否可以發文
          if not is_posting_time():
              print("不在發文時間範圍內，退出程式")
              sys.exit(0)
              
          if not check_post_count():
              print("今日發文可能已達上限，退出程式")
              sys.exit(0)
          
          # 啟動主程式
          print("符合發文條件，啟動主程式...")
          process = subprocess.Popen(["python", "-m", "src.main"])
          
          start_time = time.time()
          last_check = start_time
          
          try:
              while process.poll() is None:
                  # 檢查是否超時
                  current_time = time.time()
                  if current_time - start_time > timeout:
                      print(f"程式執行超過 {timeout} 秒，強制終止")
                      process.terminate()
                      time.sleep(5)
                      process.kill()
                      sys.exit(1)
                  
                  # 每30秒檢查一次日誌
                  if current_time - last_check >= 30:
                      print(f"已運行 {int(current_time - start_time)} 秒...")
                      last_check = current_time
                      
                      # 檢查是否已發文成功或出現錯誤
                      try:
                          if os.path.exists("logs/threads_poster.log"):
                              with open("logs/threads_poster.log", "r", encoding="utf-8") as f:
                                  content = f.read()
                                  if "發文成功" in content:
                                      print("檢測到發文成功，結束程式")
                                      process.terminate()
                                      time.sleep(5)
                                      process.kill()
                                      sys.exit(0)
                                  
                                  if "今日發文次數已達上限" in content or "不在允許發文範圍" in content:
                                      print("檢測到發文限制消息，結束程式")
                                      process.terminate()
                                      time.sleep(5)
                                      process.kill()
                                      sys.exit(0)
                                  
                                  # 查找錯誤
                                  errors = re.findall(r"(ERROR|CRITICAL).*", content)
                                  if errors:
                                      print("檢測到錯誤日誌：")
                                      for error in errors[-5:]:  # 顯示最後5條錯誤
                                          print(error)
                      except Exception as e:
                          print(f"檢查日誌時出錯: {e}")
                  
                  time.sleep(1)
                  
              # 正常結束
              print("程式已完成執行")
              sys.exit(0)
              
          except KeyboardInterrupt:
              print("接收到中斷信號，終止程式")
              process.terminate()
              time.sleep(5)
              process.kill()
              sys.exit(1)
          EOF
          
          # 運行監控腳本
          pip install pytz
          python run_with_timeout.py

      - name: 檢查日誌
        if: always()
        run: |
          if [ -d "logs" ] && [ -f "logs/threads_poster.log" ]; then
            echo "=== 日誌內容 (最後200行) ==="
            tail -n 200 logs/threads_poster.log
            
            # 提取發文結果
            echo "=== 發文結果 ==="
            grep "發文成功" logs/threads_poster.log || echo "未找到成功發文記錄"
            
            # 提取發文計劃
            echo "=== 發文計劃信息 ==="
            grep "已生成每日發文計劃" logs/threads_poster.log || echo "未找到發文計劃"
            
            # 提取等待信息
            echo "=== 等待信息 ==="
            grep "等待下次發文時間" logs/threads_poster.log | tail -n 5 || echo "未找到等待信息"
          else
            echo "找不到日誌文件"
            # 顯示當前目錄下的所有文件
            echo "=== 當前目錄內容 ==="
            ls -la
            echo "=== 日誌目錄內容(如果存在) ==="
            ls -la logs/ || echo "日誌目錄不存在"
          fi

      - name: 上傳日誌作為構件
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: threadsposter-logs-v1.2.1
          path: |
            logs/*.log
            *.log
          retention-days: 7 